export const TRIGGER_THREAD = 'TRIGGER_THREAD';

//TWEETS
export const ADD_TWEET = 'ADD_TWEET';
export const EDIT_TWEET = 'EDIT_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const TRIGGER_EDITABLE_TWEET = 'TRIGGER_EDITABLE_TWEET';
export const TRIGGER_ACTIVABLE_TWEET = 'TRIGGER_ACTIVABLE_TWEET';
export const ADD_COMMENT_TO_TWEET = 'ADD_COMMENT_TO_TWEET';
export const DELETE_COMMENT_IN_TWEET = 'DELETE_COMMENT_IN_TWEET';
export const CREATE_TWEET = 'CREATE_TWEET';
export const TRIGGER_FETCHING_TWEET = 'TRIGGER_FETCHING_TWEET';

//COMMENTS
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_ALL_COMMENTS_IN_TWEET = 'DELETE_ALL_COMMENTS_IN_TWEET';
export const TRIGGER_EDITABLE_COMMENT = 'TRIGGER_EDITABLE_COMMENT';
export const TRIGGER_ACTIVABLE_COMMENT = 'TRIGGER_ACTIVABLE_COMMENT';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENT';

//TWEETSBYTHREAD
export const LOAD_TWEETS = 'LOAD_TWEETS';
export const LOAD_TWEET = 'LOAD_TWEET';

//ERRORS
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
