export const ADD_TWEET = 'ADD_TWEET';
export const EDIT_TWEET = 'EDIT_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const TRIGGER_THREAD = 'TRIGGER_THREAD';
export const TRIGGER_EDITABLE = 'TRIGGER_EDITABLE';
